// Worker entry: the Next.js app (OpenNext), behind a small layer that
//  - sends pages opened on an old domain (tools.valuefy.ro) to the same page on the app's domain (app.uvalo.ro), with a
//    301 that keeps the path and the query (sign-in links and invitations already sent keep working). /api/ stays
//    reachable on the old domain, so other apps (the CRM's parcel centres) and pending requests are not broken;
//  - drops client-sent forwarding headers, so links in emails are built only from the real Host.
// OLD_HOSTS (comma-separated) and APP_URL can change both domains without touching the code.
// @ts-expect-error generated by `opennextjs-cloudflare build`
import { default as app } from "./.open-next/worker.js";

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

type Env = { OLD_HOSTS?: string; APP_URL?: string } & Record<string, unknown>;

export default {
  async fetch(req: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(req.url);
    const old = (env.OLD_HOSTS || "tools.valuefy.ro").split(",").map((h) => h.trim().toLowerCase()).filter(Boolean);
    if (old.includes(url.hostname.toLowerCase()) && !url.pathname.startsWith("/api/")) {
      const to = (env.APP_URL || "https://app.uvalo.ro").replace(/\/$/, "");
      return Response.redirect(`${to}${url.pathname}${url.search}`, 301);
    }
    const headers = new Headers(req.headers);
    headers.delete("x-forwarded-host");
    headers.delete("x-forwarded-proto");
    return app.fetch(new Request(req, { headers }), env, ctx);
  },
};
